wget https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.10.0.tar.xz
wget https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.10.0.tar.xz
wget https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.10.0.tar.xz
wget https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.10.0.tar.xz
wget https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.10.0.tar.xz
wget https://gstreamer.freedesktop.org/src/gst-omx/gst-omx-1.10.0.tar.xz
wget https://gstreamer.freedesktop.org/src/gst-rtsp-server/gst-rtsp-server-1.10.0.tar.xz
wget https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.10.0.tar.xz
wget https://gstreamer.freedesktop.org/src/orc/orc-0.4.26.tar.xz
wget https://gstreamer.freedesktop.org/src/gst-validate/gst-validate-1.10.0.tar.xz
wget ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.2.tar.bz2
wget ftp://ftp.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20161111-2245.tar.bz2
