##########################################
#
#This section is SENSOR TYPE.
#Type is NVP6114, NVP2422, NVP2440
#If support camera type is disable, camera monitoring can't open
#
##########################################

##########FRONT CAMERA SETTION############
#SUPPORT_CAMERATYPE_FRONT="NVP2440"
SUPPORT_CAMERATYPE_FRONT="MIPIPLK"

###########REAR CAMERA SETTION############
SUPPORT_CAMERATYPE_REAR="NVP6114"

###########AUDIO CODEC SETTION############
SUPPORT_AUDIO_CODEC="ALC5633"

###########USB CAMERA SETTION############
#SUPPORT_CAMERATYPE_USB="Y"

##########################################
#
#This section is WIFI TYPE.
#Type is
#If support wifi type is disable, wifi code can't open
#
##########################################

################WIFI SECTION##############
#ADD INFORMATION
