typedef enum {
    MLSTR_RESET=0,
    MLSTR_DONE,
    MLSTR_CAL_TOUCH_ANYWHERE,
    MLSTR_CAL_TOUCH_POINT,
    MLSTR_CAL_TOUCH_TEST,
    MLSTR_LOADING,
    MLSTR_SD_INSERTED,
    MLSTR_SD_REMOVE
    };

const unsigned int text_array[] =
{
    MLSTR_RESET,
    MLSTR_DONE,
    MLSTR_CAL_TOUCH_ANYWHERE,
    MLSTR_CAL_TOUCH_POINT,
    MLSTR_CAL_TOUCH_TEST,
    MLSTR_LOADING,
    MLSTR_SD_INSERTED,
    MLSTR_SD_REMOVE
};
