all:	fork_main.o

pthread_main.o :
	gcc -o a.out pthread_main.c  -lpthread
clean:  
	rm *.o

alarm_main.o :
	gcc -o a.out alarm_main.c  -lpthread -g

fork_main.o :
	gcc -o a.out fork_main.c  -lpthread -g
