obj-m := hello_proc.o 

#KDIR  := $(KERNEL_SRC)
KDIR  := /lib/modules/$(shell uname -r)/build
PWD   := $(shell pwd)

default:
		$(MAKE) -C $(KDIR) M=$(PWD) modules

clean:
		$(MAKE) -C $(KDIR) M=$(PWD) clean
