'\" t
.\"     Title: cheese
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 06/27/2017
.\"    Manual: User Commands
.\"    Source: Cheese 3.10.2
.\"  Language: English
.\"
.TH "CHEESE" "1" "06/27/2017" "Cheese 3\&.10\&.2" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cheese \- tool to take pictures and videos from your webcam
.SH "SYNOPSIS"
.HP \w'\fBcheese\fR\ 'u
\fBcheese\fR [option...]
.SH "DESCRIPTION"
.PP
\fBcheese\fR
uses your webcam to take photos and videos, applies fancy special effects and lets you share the fun with others\&. It was written as part of Google\*(Aqs 2007 Summer of Code lead by daniel g\&. siegel and mentored by Raphaël Slinckx\&. Under the hood, Cheese uses GStreamer to apply fancy effects to photos and videos\&. With Cheese it is easy to take photos of you, your friends, pets or whatever you want and share them with others\&. After the success of the Summer of Code, the development continued and we are still looking for people with nice ideas and patches ;)
.SH "INVOCATION"
.PP
\fBcheese\fR
takes a list of options as arguments\&.
.SS "Options"
.PP
\fB\-\-wide\fR, \fB\-w\fR
.RS 4
Start in wide mode, with the thumbnails to the right of the video preview\&.
.RE
.PP
\fB\-\-device=DEVICE\fR, \fB\-d DEVICE\fR
.RS 4
Use the supplied DEVICE as the video capture device\&.
.RE
.PP
\fB\-\-fullscreen\fR, \fB\-f\fR
.RS 4
Start in fullscreen mode\&.
.RE
.PP
\fB\-\-help\fR, \fB\-h\fR
.RS 4
Print brief help and exit\&.
.RE
.PP
\fB\-\-version\fR, \fB\-v\fR
.RS 4
Print the version and exit\&.
.RE
.SH "SEE ALSO"
.PP
Cheese help manual
.SH "AUTHOR"
.PP
\fBcheese\fR
was written by Daniel G\&. Siegel
<dgsiegel@gnome\&.org>, Jaap A\&. Haitsma
<jaap@haitsma\&.org>, Filippo Argiolas
<fargiolas@gnome\&.org>, Yuvaraj Pandian T
<yuvipanda@yuvi\&.in>, Luciana Fujii Pontello
<luciana@fujii\&.eti\&.br>
and David King
<amigadave@amigadave\&.com>\&.
.PP
This manual page was written by David King
<amigadave@amigadave\&.com>\&.
